### ISSUE TITLE
macvim failed to build on 10.6.8

### ISSUE THREAD

**Issue by axtens** [Homebrew/legacy-homebrew#38047]
==> Upgrading macvim
==> Downloading https://github.com/macvim-dev/macvim/archive/snapshot-74.tar.gz
Already downloaded: /Library/Caches/Homebrew/macvim-7.4-74.tar.gz
==> ./configure --with-features=huge --enable-multibyte --with-macarchs=x86_64 --enable-perlinterp --enable-rubyinterp --enable-tclinterp --with-tlib
==> make
if_ruby.c:706: error: 'rb_encoding' undeclared (first use in this function)
if_ruby.c:706: error: 'enc' undeclared (first use in this function)
make[1]: *** [objects/if_ruby.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [first] Error 2

gist: https://gist.github.com/axtens/e49c260bc97b6b4bb2a2

**Comment by mistydemeo** [comment]
Could you post the output of `brew gist-logs macvim`, please? Thanks!

**Comment by axtens** [comment]
https://gist.github.com/09e838289f9d9d4fd8e9

Done!

**Comment by mistydemeo** [comment]
Looks like Macvim isn't compatible with the system Ruby in 10.6.

**Comment by axtens** [comment]
bash-4.3$ brew install ruby
Warning: ruby-2.2.1 already installed

Which version is needed?

**Comment by chdiza** [comment]
If memory serves, MacVim can't be made to link to a non-system ruby (because Vim can't).  If that's right, then @axtens could work around this by commenting out the `--enable-rubyinterp` line in the MacVim formula.

@mistydemeo I could swear that MacVim *used to be* compatible with Snow Leo's ruby.  Perhaps they mucked around with ruby detection for Linux or Windows and nobody noticed that it broke things for OSX?

**Comment by jacknagel** [comment]
I would `brew unlink ruby` and then try again.

**Comment by sammcj** [comment]
Reproducible on Yosemite with standard system ruby `2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]`

```
brew install macvim --with-lua --override-system-vim
==> Downloading https://github.com/macvim-dev/macvim/archive/snapshot-74.tar.gz
Already downloaded: /Library/Caches/Homebrew/macvim-7.4-74.tar.gz
==> ./configure --with-features=huge --enable-multibyte --with-macarchs=x86_64 --enable-perlinterp --en
==> make
clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.10 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       -o objects/memfile.o memfile.c
1 error generated.
make[1]: *** [objects/if_ruby.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [first] Error 2
```

**Comment by sammcj** [comment]
Just fixed it, sure enough, reinstalled xcode dev tools fixed it:

```
xcode-select --install
# Complained about permissions of one file so had to change ownership as such:
sudo chown root /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/lib/dyld_sim
```

**Comment by andistern** [comment]
```code
rvm system
```
did it for me ( Mac OSX 10.6.8)

**Comment by BeauBouchard** [comment]
Issue still happens on Mac OSX 10.10.2, 
failed install

**Comment by mqs2015** [comment]
similar issue on Mac OS X 10.10.3 when trying to do:

brew install macvim --override-system-vim

checking whether we are cross compiling... configure: error: in `/private/tmp/macvim20150504-570-1rhvq56/macvim-Snapshot-76/src':
configure: error: cannot run C compiled programs.

here is what I get for: 

brew gist-logs macvim 
https://gist.github.com/anonymous/d339b0dff034e952dc1b

**Comment by mqs2015** [comment]
Just fixed it. In my case it was a problem of python. I had in $PATH the Canopy version of python, just erased that in it worked.

**Comment by SephVelut** [comment]
OSX 10.10.3 here. Using a MAMP bin'ed python caused the issue for me. Altering the $PATH fixed it.

**Comment by jacknagel** [comment]
The root cause is the same as #33705, as discussed in #40255. vim's configure script is misdetecting the header directory for ruby 1.8:

```
checking Ruby header files... /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/universal-darwin12.0
```

**Comment by gsz** [comment]
I experienced this problem when MacVim tried to compile against homebrew ruby.

```
configure:7082: checking Ruby header files
configure:7086: result: /usr/local/Cellar/ruby/2.0.0-p247/include/ruby-2.0.0
```

In this particular case the culprit turned out to be those lines from if_ruby.c:

```
#ifdef FEAT_GUI_MACVIM
# include <Ruby/ruby.h>
#else
# include <ruby.h>
#endif
#ifdef RUBY19_OR_LATER
# ifdef FEAT_GUI_MACVIM
#  include <Ruby/ruby/encoding.h>
# else
#  include <ruby/encoding.h>
# endif
#endif
```
MacVim compilation assumed that header files are one nesting level deeper than they actually are. A simple workaround was to navigate to the Ruby headers dir and do:

```
mkdir ruby
cp *.h ruby/
```

Compilation was successful afterwards.

This doesn't look like the same problem as the one in the referenced issue with vanilla Vim. That one has linking errors.

**Comment by nicolaje** [comment]
xcode-select --install # Did the trick for me

xcode-select --install
xcode-select: note: install requested for command line developer tools

**Comment by MikeMcQuaid** [comment]
Closing this out as it's an upstream issue that needs fixed there rather than here.
