### ISSUE TITLE
macvim fails to build on Yosemite 10.10 with _SC_PHYS_PAGES error

### ISSUE THREAD

**Issue by fxer** [Homebrew/legacy-homebrew#47026]
Running latest Xcode 7.2 on Yosemite 10.10

```
miniserver:/ ladmin$ brew update
Already up-to-date.
miniserver:/ ladmin$ brew doctor
Your system is ready to brew.
miniserver:/ ladmin$ brew install macvim
==> Downloading https://github.com/macvim-dev/macvim/archive/snapshot-85.tar.gz
Already downloaded: /Library/Caches/Homebrew/macvim-7.4-85.tar.gz
==> ./configure --with-features=huge --enable-multibyte --with-macarchs=x86_64 -
==> make
Last 15 lines from /Users/ladmin/Library/Logs/Homebrew/macvim/02.make:
clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -F/usr/local/Cellar/python/2.7.11/Frameworks -I/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7 -fno-strict-aliasing -fno-common -dynamic -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch x86_64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      -I/System/Library/Frameworks/Tcl.framework/Headers  -D_REENTRANT=1  -D_THREAD_SAFE=1  -D_DARWIN_C_SOURCE=1   -o objects/misc1.o misc1.c
clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -F/usr/local/Cellar/python/2.7.11/Frameworks -I/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7 -fno-strict-aliasing -fno-common -dynamic -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch x86_64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      -I/System/Library/Frameworks/Tcl.framework/Headers  -D_REENTRANT=1  -D_THREAD_SAFE=1  -D_DARWIN_C_SOURCE=1   -o objects/misc2.o misc2.c
clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -F/usr/local/Cellar/python/2.7.11/Frameworks -I/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7 -fno-strict-aliasing -fno-common -dynamic -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch x86_64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      -I/System/Library/Frameworks/Tcl.framework/Headers  -D_REENTRANT=1  -D_THREAD_SAFE=1  -D_DARWIN_C_SOURCE=1   -o objects/move.o move.c
clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -F/usr/local/Cellar/python/2.7.11/Frameworks -I/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7 -fno-strict-aliasing -fno-common -dynamic -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch x86_64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      -I/System/Library/Frameworks/Tcl.framework/Headers  -D_REENTRANT=1  -D_THREAD_SAFE=1  -D_DARWIN_C_SOURCE=1   -o objects/mbyte.o mbyte.c
clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -F/usr/local/Cellar/python/2.7.11/Frameworks -I/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7 -fno-strict-aliasing -fno-common -dynamic -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch x86_64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      -I/System/Library/Frameworks/Tcl.framework/Headers  -D_REENTRANT=1  -D_THREAD_SAFE=1  -D_DARWIN_C_SOURCE=1   -o objects/normal.o normal.c
clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -F/usr/local/Cellar/python/2.7.11/Frameworks -I/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7 -fno-strict-aliasing -fno-common -dynamic -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch x86_64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      -I/System/Library/Frameworks/Tcl.framework/Headers  -D_REENTRANT=1  -D_THREAD_SAFE=1  -D_DARWIN_C_SOURCE=1   -o objects/ops.o ops.c
clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -F/usr/local/Cellar/python/2.7.11/Frameworks -I/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7 -fno-strict-aliasing -fno-common -dynamic -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch x86_64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      -I/System/Library/Frameworks/Tcl.framework/Headers  -D_REENTRANT=1  -D_THREAD_SAFE=1  -D_DARWIN_C_SOURCE=1   -o objects/option.o option.c
clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -F/usr/local/Cellar/python/2.7.11/Frameworks -I/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7 -fno-strict-aliasing -fno-common -dynamic -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch x86_64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      -I/System/Library/Frameworks/Tcl.framework/Headers  -D_REENTRANT=1  -D_THREAD_SAFE=1  -D_DARWIN_C_SOURCE=1   -o objects/os_unix.o os_unix.c
os_unix.c:569:22: error: use of undeclared identifier '_SC_PHYS_PAGES'
        pagecount = sysconf(_SC_PHYS_PAGES);
                            ^
1 error generated.
make[1]: *** [objects/os_unix.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [first] Error 2

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
macvim: disable ruby integration on 10.6 https://github.com/Homebrew/homebrew/pull/40255
macvim failed to build on 10.6.8 https://github.com/Homebrew/homebrew/issues/38047
```

**Comment by DomT4** [comment]
Can we get a full `brew gist-logs macvim`? Thanks!

**Comment by bfontaine** [comment]
Note that MacVim was very recently updated; run You should `brew update` and try again.

**Comment by fxer** [comment]
Getting the same error on the latest macvim (snapshot 86), here is the full gist-log: https://gist.github.com/d5477582b31570aa8694

**Comment by theknix** [comment]
Afaik Darwin doesn't support `_SC_PHYS_PAGES`.
Looks like a bug in upstream.

**Comment by theknix** [comment]
I might have been mistaken.
It looks like `_SC_PHYS_PAGES` is available on my El Capitan 10.11.2 machine with the latest Xcode 7.2 installed.

@fxer can you check if `_SC_PHYS_PAGES` is defined in `/usr/include/unistd.h`?

**Comment by fxer** [comment]
Yes it's defined in the file: `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/unistd.h`

The MacOSX10.11.sdk is the only SDK available in Xcode 7.2 even on Yosemite.

**Comment by rgujral-ari** [comment]
Saw this problem today, full logs attached https://gist.github.com/5ae5a1a808047d8ebc89

**Comment by ilovezfs** [comment]
@rgujral-ari Your log indicates you're using Yosemite.

**Comment by ilovezfs** [comment]
@fxer @digoot @apjanke @DomT4 OK, I was able to reproduce the _SC_PHYS_PAGES issue. It occurs if you currently have Xcode.app installed && CLT installed && brew python built from source while the CLT was NOT installed. It is caused by superenv, which when you call "make" (as opposed to "xcrun make") will refurbish your CFLAGS whether you asked it to or not.

When python is built with Xcode and CLT present, you get python-config --cflags
-I/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7 -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes

When python is built with only Xcode present, you get python-config --cflags
-I/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7 -fno-strict-aliasing -fno-common -dynamic -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes

superenv
strips
["-Wall", "-isysroot", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk", "-g", "-O3", "-Wall", "-Wstrict-prototypes"]

and adds
["-w", "-Os", "-march=native", "-isystem/usr/local/include", "-isystem/usr/include/libxml2", "-isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers"]

The removal of "-isysroot", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk" causes it to blow up because _SC_PHYS_PAGES is defined in the SDK's unistd.h but not defined in /usr/include/unistd.h.

So during configure MacVim finds it defined and during compilation it finds it undefined.

You can workaround the problem by reinstalling python from source while both Xcode and the CLT are installed, by using the bottled python, by uninstalling brew's python, or by changing the formula to run "xcrun", "make" instead of "make"

**Comment by digoot** [comment]
That worked for me:

```
$ brew install macvim --env-std --with-override-system-vim
==> Downloading https://github.com/macvim-dev/macvim/archive/snapshot-99.tar.gz
Already downloaded: /Library/Caches/Homebrew/macvim-7.4-99.tar.gz
==> ./configure --with-features=huge --enable-multibyte --with-macarchs=x86_64 --enable-perlinterp -
==> make
==> Caveats
.app bundles were installed.
Run `brew linkapps macvim` to symlink these to /Applications.
==> Summary
🍺  /usr/local/Cellar/macvim/7.4-99: 2,068 files, 32.8M, built in 1 minute 11 seconds
```

Thank you so much!

**Comment by MikeMcQuaid** [comment]
We provide a Yosemite bottle now.
