### ISSUE TITLE
Modules failed to build on OS X 10.10.5

### ISSUE THREAD

**Issue by bravepetrelc** [Homebrew/legacy-homebrew#49696]
I can not install Modules via brew on 10.10.5, the error is:

	brew install modules
	==> Downloading https://downloads.sourceforge.net/project/modules/Modules/module
	Already downloaded: /Library/Caches/Homebrew/modules-3.2.10.tar.bz2
	==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/modules/3.2.10
	==> make install
	Last 15 lines from /Users/xychen/Library/Logs/Homebrew/modules/02.make:
	   __builtin___strncpy_chk (dest, src, len, __darwin_obsz (dest))
	                                         ^
	utility.c:1059:23: error: expected expression
	                buffer[ LMSPLIT_SIZE] = '\0';
	                                    ^
	utility.c:1064:30: error: expected expression
	                 lmfiles_len -= LMSPLIT_SIZE;
	                                            ^
	 utility.c:1070:36: error: expected expression
                     (escaped + count*LMSPLIT_SIZE), shell_cmd_separator);
	                                                  ^
	 7 errors generated.
	 make[1]: *** [modulecmd-utility.o] Error 1
	 make[1]: *** Waiting for unfinished jobs....
	 make: *** [install-recursive] Error 1

gist-logs: [https://gist.github.com/5e27b2e86f3af6755e8b](https://gist.github.com/5e27b2e86f3af6755e8b)

results of brew config:

	HOMEBREW_VERSION: 0.9.5
	ORIGIN: https://github.com/Homebrew/homebrew
	HEAD: 99602144b6becf7d84309b14bb5bbd4e6b8fd746
	Last commit: 3 hours ago
	HOMEBREW_PREFIX: /usr/local
	HOMEBREW_REPOSITORY: /usr/local
	HOMEBREW_CELLAR: /usr/local/Cellar
	HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
	CPU: quad-core 64-bit broadwell
	OS X: 10.10.5-x86_64
	Xcode: 7.2.1
	CLT: 7.2.0.0.1.1447826929
	Clang: 7.0 build 700
	X11: 2.7.8 => /opt/X11
	System Ruby: 2.0.0-p481
	Perl: /usr/bin/perl
	Python: /usr/bin/python
	Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.3.0/bin/ruby
	Java: 1.6.0_65-b14-466.1

**Comment by DomT4** [comment]
It's okay here on 10.11.4. Can you try removing the non-prefixed `coreutils` from your `$PATH` and trying again? It's nice to rule that out before we hunt further.

**Comment by bravepetrelc** [comment]
@DomT4 Thanks for your reply. I removed coreutils and re-install modules again, but it output the same errors. Updated gist-logs can be seen here: [https://gist.github.com/f343b65971dbd3fcbbbc](https://gist.github.com/f343b65971dbd3fcbbbc)

**Comment by dunn** [comment]
It's failing for me even earlier: https://gist.github.com/anonymous/bfbf6eec7aad63b4f8c0

Did you install a newer Tcl, from `homebrew/dupes` or elsewhere?

**Comment by bravepetrelc** [comment]
@dunn I did not install Tcl. Here are all the formulae installed through homebrew:

> $ brew list
> aria2	   convmv     duti     libyaml	   openssl   rmtrash  wget
> brew-cask  coreutils  hexedit  media-info  readline  ruby     xz

**Comment by dunn** [comment]
Gotcha.  `-I/System/Library/Frameworks/Tcl.framework/Versions/8.5/Headers` is being passed to Clang, though; does that directory exist on your system?

**Comment by bravepetrelc** [comment]
@dunn As you said, this directory actually exists in my system. How to solve the problem?

**Comment by dunn** [comment]
Oh, I don't think that's why it's failing for you; it's the lack of a newer Tcl (such as yours) that it causing it to fail even earlier for me.

**Comment by DomT4** [comment]
This is a little odd. On Alex's install the line is:
```
modulecmd-main.o modulecmd-error.o modulecmd-getopt.o modulecmd-version.o -L/usr/local/lib -ltcl8.6 
```
Which causes failure because it can't find `-ltcl8.6` to link.

Mine is:
```
modulecmd-main.o modulecmd-error.o modulecmd-getopt.o modulecmd-version.o -F/System/Library/Frameworks -framework Tcl 
```
Which works fine. OP doesn't even get that far :confused:.

**Comment by DomT4** [comment]
No build problems on CI. Managed to add a bottle in https://github.com/Homebrew/homebrew/commit/de2d828f21038f6cc277abe188253c3dd7945cc2. Presumably this is some local variation, but unsure quite what.

**Comment by UniqMartin** [comment]
Closing as this doesn't seem to be reproducible. Feel free to report back if things change, but I can't see us being able to help you at this point (except for pointing you at the bottles that are now available).
