### ISSUE TITLE
qscintilla2 fails to build on 10.11: sip files generating qt5 API, but only qt4 installed

### ISSUE THREAD

**Issue by ejtttje** [Homebrew/legacy-homebrew#41464]
When generating the python bindings, the sip files all die with error:

```
./sipQsciQsciLexerCSharp.cpp:194:43: error: no viable conversion from 'const QMetaMethod' to 'const char *'
        QsciLexerCSharp::disconnectNotify(a0);
                                          ^~
/Volumes/Xcode/Brew/Cellar/qt/4.8.7/lib/QtCore.framework/Versions/4/Headers/qobject.h:291:47: note: passing argument to parameter 'signal' here
    virtual void disconnectNotify(const char *signal);
                                              ^
./sipQsciQsciLexerCSharp.cpp:212:40: error: no viable conversion from 'const QMetaMethod' to 'const char *'
        QsciLexerCSharp::connectNotify(a0);
                                       ^~
/Volumes/Xcode/Brew/Cellar/qt/4.8.7/lib/QtCore.framework/Versions/4/Headers/qobject.h:290:44: note: passing argument to parameter 'signal' here
    virtual void connectNotify(const char *signal);
                                           ^
```

QT4 used the char* argument for these methods, QT5 switched it to use QMetaMethod instead.
So it looks like sip is generating QT5 calls even though I only have QT4 installed?  Not sure if this is a bug/issue with sip, or something in the build configuration for qscintilla...

**Comment by tdsmith** [comment]
Can you share the output of `brew gist-logs qscintilla2` please?

**Comment by louis-web** [comment]
```
bogon:eric6-6.0.7 louis$ brew install QScintilla2 --with-python3
==> Installing qscintilla2 dependency: pyqt
==> Downloading https://downloads.sf.net/project/pyqt/PyQt4/PyQt-4.11.3/PyQt-mac
==> Downloading from http://nchc.dl.sourceforge.net/project/pyqt/PyQt4/PyQt-4.11
######################################################################## 100.0%
==> python configure.py --confirm-license --bindir=/usr/local/Cellar/pyqt/4.11.3
==> python configure-ng.py --confirm-license --bindir=/usr/local/Cellar/pyqt/4.1
==> make
==> make install
==> make clean
==> python3 configure.py --confirm-license --bindir=/usr/local/Cellar/pyqt/4.11.
==> python3 configure-ng.py --confirm-license --bindir=/usr/local/Cellar/pyqt/4.
==> make
==> make install
==> make clean
==> Caveats
Phonon support is broken.

==> Summary
🍺  /usr/local/Cellar/pyqt/4.11.3: 617 files, 34M, built in 7.9 minutes
==> Installing qscintilla2
==> Downloading https://downloads.sf.net/project/pyqt/QScintilla2/QScintilla-2.8
######################################################################## 100.0%
==> qmake qscintilla.pro -config release -spec unsupported/macx-clang-libc++
==> make
==> make install
==> python configure.py -o /usr/local/Cellar/qscintilla2/2.8.4/lib -n /usr/local
==> make
/usr/local/Cellar/qt/4.8.7/lib/QtCore.framework/Versions/4/Headers/qobject.h:290:44: note: passing argument to parameter 'signal' here
    virtual void connectNotify(const char *signal);
                                           ^
2 errors generated.
make: *** [sipQsciQsciLexerBatch.o] Error 1

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
qscintilla2 doesn't support pyqt5 (only pyqt4?) https://github.com/Homebrew/homebrew/issues/37591
qscintilla2 fails to build on 10.11: sip files generating qt5 API, but only qt4 installed https://github.com/Homebrew/homebrew/issues/41464
bogon:eric6-6.0.7 louis$ brew list
cmake			openssl			ruby21
gdbm			pcre			saltstack
libffi			pkg-config		sip
libimobiledevice	pyqt			sqlite
libplist		pyqt5			swig304
libtasn1		python			usbmuxd
libusb			python3			xz
libxml2			qt			zeromq
libyaml			qt5
makedepend		readline
bogon:eric6-6.0.7 louis$ brew install QScintilla2 --with-python3
==> Downloading https://downloads.sf.net/project/pyqt/QScintilla2/QScintilla-2.8
Already downloaded: /Library/Caches/Homebrew/qscintilla2-2.8.4.tar.gz
==> qmake qscintilla.pro -config release -spec unsupported/macx-clang-libc++
==> make
==> make install
==> python configure.py -o /usr/local/Cellar/qscintilla2/2.8.4/lib -n /usr/local
==> make
                                           ^
2 errors generated.
2 errors generated.
make: *** [sipQsciQsciLexerBatch.o] Error 1
make: *** [sipQsciQsciLexerBash.o] Error 1

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
qscintilla2 doesn't support pyqt5 (only pyqt4?) https://github.com/Homebrew/homebrew/issues/37591
qscintilla2 fails to build on 10.11: sip files generating qt5 API, but only qt4 installed https://github.com/Homebrew/homebrew/issues/41464
bogon:eric6-6.0.7 louis$ 
```

**Comment by apjanke** [comment]
I'm seeing a similar error on my 10.11 beta test box. Here's my `brew gist-logs`.

https://gist.github.com/13d029521a2952a49870

**Comment by yarko** [comment]
I'm seeing this (exact same thing) on os/x 10.10.5

**Comment by ecerrillo** [comment]
Same here!

https://gist.github.com/d190af428dff04c61643

**Comment by tdsmith** [comment]
¯\\\_(ツ)\_/¯ I don't know how to debug this. It looks like everything is configured correctly: https://gist.github.com/anonymous/d190af428dff04c61643#file-04-python-L15-L30

I suggest reaching out to the qscintilla developers. It looks like it's been raised on this thread: https://www.riverbankcomputing.com/pipermail/qscintilla/2015-September/001067.html -- the correct qmake is being invoked and PyQt4 is being correctly selected.

**Comment by schoeps** [comment]
I can build qscintilla2 on El Capitan without the python bindings which I do not need (for Octave). May I suggest that the user can disable the python bindings? see e.g. https://gist.github.com/6d3f1008b9912f70f7ce

**Comment by tdsmith** [comment]
Upstream issue: https://www.riverbankcomputing.com/pipermail/qscintilla/2015-October/001068.html

**Comment by dakcarto** [comment]
Ran into this, I then bumped my local formulae of `pyqt` and `qscintilla2` to versions 4.11.4 and 2.9 respectively and had no problems compiling/installing (even on OS X 10.7). Not sure if this addresses this particular issue, but it is worth noting that the version bumps may be a good first step towards a resolution.

**Comment by apjanke** [comment]
That looks like a fix. If I bump both versions, they build and install on OS X 10.11 for me. Submitting PRs for the version bumps...

**Comment by ecerrillo** [comment]
It works now!

**Comment by McPo** [comment]
I made the changes referenced in the PR, and disabled the OSX sandbox.

Continues to fail with same issue
'''
An internal error occured.  Please report all the output from the program,
including the following traceback, to support@riverbankcomputing.com.
Traceback (most recent call last):
  File "configure.py", line 1664, in <module>
    _main(sys.argv, module_config)
  File "configure.py", line 1637, in _main
    target_config.introspect_pyqt(module_config)
  File "configure.py", line 860, in introspect_pyqt
    from PyQt4 import QtCore
RuntimeError: the sip module implements API v11.0 to v11.2 but the PyQt4.QtCore module requires API v10.1

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
Qscintilla2 2.9 https://github.com/Homebrew/homebrew/pull/44726
qscintilla2 doesn't support pyqt5 (only pyqt4?) https://github.com/Homebrew/homebrew/issues/37591
qscintilla2 fails to build on 10.11: sip files generating qt5 API, but only qt4 installed https://github.com/Homebrew/homebrew/issues/41464
'''

**Comment by boltomli** [comment]
I rebuilt pyqt and sip, etc. then install 2.9 successfully. You might try that.

**Comment by UniqMartin** [comment]
The `qscintilla` formula has been updated to 2.9.1 very recently. Closing as apparently this should resolve the issue reported here. (Please report back if that's not the case.)
