### ISSUE TITLE
gcc failed to build on 10.6.8

### ISSUE THREAD

**Issue by holiveros** [Homebrew/legacy-homebrew#47741]
Trying to install wine, build fails on gcc prerequisite.

Trying to install gcc via brew install gcc fails with:
```
==> Patching
patching file gcc/jit/Make-lang.in
patching file gcc/jit/jit-playback.c
Hunk #1 succeeded at 2470 with fuzz 2 (offset 54 lines).
==> ../configure --build=x86_64-apple-darwin10.8.0 --prefix=/usr/local/Cellar/gcc/5.3.0 --libdir=/usr/local/Cellar/gcc/5.3.0/lib/gcc/5 --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-5
==> make bootstrap
Last 15 lines from /Users/humberto/Library/Logs/Homebrew/gcc/02.make:
../../gcc/hash-table.h:1073:43: error: out-of-line definition of 'traverse' does not match any declaration in 'hash_table<type-parameter-0-0, Allocator, false>'
hash_table<Descriptor, Allocator, false>::traverse (Argument argument)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
../../gcc/hash-table.h:1623:42: error: out-of-line definition of 'traverse_noresize' does not match any declaration in 'hash_table<type-parameter-0-0, Allocator, true>'
hash_table<Descriptor, Allocator, true>::traverse_noresize (Argument argument)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
../../gcc/hash-table.h:1649:42: error: out-of-line definition of 'traverse' does not match any declaration in 'hash_table<type-parameter-0-0, Allocator, true>'
hash_table<Descriptor, Allocator, true>::traverse (Argument argument)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
4 errors generated.
make[3]: *** [build/hash-table.o] Error 1
rm gcc.pod
make[2]: *** [all-stage1-gcc] Error 2
make[1]: *** [stage1-bubble] Error 2
make: *** [bootstrap] Error 2
```

Not an expert with building gcc, but seems as if a file were missing and/or an ignored ifdef/macro.

System is Snow Leopard (10.6.8), on a case-sensitive filesystem ;)

Also tried the same on a Mavericks (10.9) installation, no case-sensitive FS; works like a charm there.

Gist:
https://gist.github.com/anonymous/3079b219d6223d4f8c72

Anyone has had issues building gcc on this platform?

**Comment by mulle-nat** [comment]
I have the same problem, also in 10.6.8.

**Comment by mistydemeo** [comment]
Does it work if you do `brew install gcc --cc=gcc-4.2`?

**Comment by mistydemeo** [comment]
Sorry, I see you don't have gcc-4.2 installed. Try `brew install homebrew/dupes/apple-gcc42` first, then the command I suggested.

**Comment by mulle-nat** [comment]
I read some of your other comments and I am now trying to build with Xcode 3.2 and --use-gcc, instead of Xcode-4.2 and clang. Lets see how it goes. homebrew/dupes/apple-gcc42 only works for 10.7 it seems.

**Comment by mulle-nat** [comment]
It worked. I installed Xcode-3.2 parallel to my existing Xcode-4.2 into `/Xcode-3.2` and then said:

```console
sudo xcode-select -switch /Xcode-3.2
brew install gcc --cc=gcc-4.2
```

Interestingly I could not compile gcc47, which I thought would have been a more conservative pick.

**Comment by UniqMartin** [comment]
This seems to be resolved, but just in case it's not:

Sorry, but 10.6 is fairly old and not officially supported by Homebrew (as indicated by the output that `brew doctor` provides). If you can come up with a solution, feel free to submit as a PR and we'll happily accept, but currently there's nothing we can help you with directly.
