### ISSUE TITLE
rtorrent failed to build on 10.11.2 with --with-xmlrpc-c

### ISSUE THREAD

**Issue by ikirudennis** [Homebrew/legacy-homebrew#46957]
I just upgraded to El Capitan, and my previously-installed version of rtorrent would no longer run (not that I necessarily expected it to).  I `brew rm`-ed libtorrent rtorrent and xmlrp-c, and then tried reinstalling all 3.  I've also reinstalled all dependencies.  The only way to successfully build rtorrent is by not including `--with-xmlrpc-c`.  When included, the error I get is: `ld: symbol(s) not found for architecture x86_64`. I've spent some time looking through the rtorrent issues here on github and the rest of the internet, but nothing seems to help.
Gist logs available here: https://gist.github.com/anonymous/b257d6edb6c8b810b8ad
Please let me know if more information is needed.

**Comment by hautonjt** [comment]
Did you try reinstalling gcc?

**Comment by ikirudennis** [comment]
I did.  I also tried installing with gcc-4.9 and gcc-5.  No luck on either.  However, the previously-installed version of rtorrent does work now.

**Comment by coltonTB** [comment]
Seeing the same thing here. Hoping for a fix soon!

**Comment by dunn** [comment]
Could one of you try building the software outside of Homebrew? That way we can determine if it's an upstream issue or not. Thanks!

**Comment by ikirudennis** [comment]
I finally got a chance to try building this.  But it's a bit difficult to figure out if I'm doing something wrong or if it just doesn't work.  The issue I'm having is that rtorrent needs the matching libtorrent version in order to build.  And when I try to build libtorrent it fails almost immediately with an error about a missing file (tr1/functional, if anyone's curious).  So I don't know if I'm missing some step in the configure process which should create that file.  For right now, I don't have more time to devote to this, but maybe I will in the future.

**Comment by ainstushar** [comment]
Not sure if my issue is related to this one or not, here's what I get when i run ``brew install rtorrent``

````
Last 15 lines from /Users/ainstushar/Library/Logs/Homebrew/rtorrent/03.make:
      std::vector<torrent::File*, std::allocator<torrent::File*> >::_M_range_check(unsigned long) const in libsub_root.a(command_download.o)
      std::vector<torrent::Tracker*, std::allocator<torrent::Tracker*> >::_M_range_check(unsigned long) const in libsub_ui.a(element_tracker_list.o)
      std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::at(unsigned long) const in libsub_display.a(window_file_list.o)
      std::vector<torrent::Tracker*, std::allocator<torrent::Tracker*> >::_M_range_check(unsigned long) const in libsub_display.a(window_tracker_list.o)
  "std::basic_ostream<char, std::char_traits<char> >& std::operator<< <char, std::char_traits<char>, std::allocator<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)", referenced from:
      _main in main.o
      core::DownloadFactory::log_created(core::Download*, torrent::Object*)    in libsub_core.a(download_factory.o)
      core::DownloadFactory::receive_load()      in libsub_core.a(download_factory.o)
      utils::Lockfile::locked_by_as_string[abi:cxx11]() const in libsub_utils.a(lockfile.o)
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[3]: *** [rtorrent] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
````

Building from source I get:
````
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in doc
make[2]: Nothing to be done for `all'.
Making all in src
Making all in core
g++ -DHAVE_CONFIG_H -I. -I../..  -I. -I./.. -I../..   -g -O2 -g -DDEBUG -D_THREAD_SAFE    -I/usr/local/Cellar/libtorrent/0.13.6/include -I/usr/local/Cellar/xmlrpc-c/1.39.07/include  -MT curl_get.o -MD -MP -MF .deps/curl_get.Tpo -c -o curl_get.o curl_get.cc
In file included from curl_get.cc:44:
In file included from ./../globals.h:41:
../../rak/priority_queue_default.h:40:10: fatal error: 'tr1/functional' file not found
#include <tr1/functional>
         ^
1 error generated.
make[3]: *** [curl_get.o] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
````
Hopefully that helps.

**Comment by cwackerman** [comment]
I have the same error as @ainstushar on a fresh install of El Capitan. Ran `brew update` and `brew doctor` without any issues. The gist-logs can be found [here](https://gist.github.com/5bd9f011133c220b002c).

**Comment by luxus** [comment]
i can confirm that i have the same errors like @ainstushar

**Comment by luxus** [comment]
@dunn can i help you somehow to fix this? it build without xmlrpc-c. but without it torrent is not really useful :/

**Comment by dunn** [comment]
@luxus Can you try building it outside of Homebrew?  If it still fails, then it's something we can report upstream.

**Comment by luxus** [comment]
sorry @dunn im not such a pro with building stuff from source.. when i try to build rtorrent from source  i got the same error message like @ainstushar (3 post above)
i tried to brew rtorrent on my second make and was able to build it 
but i got this warning message
'''
Warning: rtorrent dependency xmlrpc-c was built with a different C++ standard
library (libc++ from clang). This may cause problems at runtime.
'''
when i run rtorrent it starts but xmlrpc is not working

**Comment by luxus** [comment]
@dunn 
i got some free time today and tried to build again from source code of the website, switching to gcc49 and end up with a similar error https://gist.github.com/luxus/1df161ab48a92119e569

**Comment by dunn** [comment]
Is that still within Homebrew, though?

**Comment by DomT4** [comment]
A while ago someone fixed the build to start building with Clang rather than GCC, but the PR went inactive and was closed. It'd be interesting to see if that was picked back up whether this still reproduces under Clang; GCC can behave a little... oddly sometimes on OS X.

**Comment by IeUz** [comment]
Any solutions to this?

**Comment by luxus** [comment]
perhaps this helps? https://github.com/pyroscope/rtorrent-ps/issues/21

**Comment by luxus** [comment]
https://github.com/Homebrew/homebrew/pull/49675 possible fix.

**Comment by MikeMcQuaid** [comment]
We've boneyarded `rtorrent` now so no longer support it.
