### ISSUE TITLE
harbour formula can't find "cairo.h" using --with-x11 option

### ISSUE THREAD

**Issue by endersonmaia** [Homebrew/legacy-homebrew#48341]
I'm having trouble compiling the Harbour formula using `--with-x11`.

I attached the logs of the failing build with homebrew.

There's a conversation that moght be relevant on vszakats/harbour-core#195.

```
✗ brew --version
Homebrew 0.9.5 (git revision dbb25; last commit 2016-01-21)
```

[make.fail-with-homebrew.txt](https://github.com/Homebrew/homebrew/files/100126/make.fail-with-homebrew.txt)

**Comment by dunn** [comment]
Looks like the X11 build requires Cairo:
```
In file included from ../../../../../contrib/hbcairo/text.c:47:
../../../../../contrib/hbcairo/hbcairo.h:53:10: fatal error: 'cairo.h' file not found
#include "cairo.h"
         ^
In file included from ../../../../../contrib/hbcairo/ps.c:47:
../../../../../contrib/hbcairo/hbcairo.h:53:10: fatal error: 'cairo.h' file not found
#include "cairo.h"
         ^
1 error generated.
1 error generated.
In file included from ../../../../../contrib/hbcairo/util.c:47:
../../../../../contrib/hbcairo/hbcairo.h:53:10: fatal error: 'cairo.h' file not found
#include "cairo.h"
         ^
1 error generated.
In file included from ../../../../../contrib/hbcairo/surface.c:47:
../../../../../contrib/hbcairo/hbcairo.h:53:10: fatal error: 'cairo.h' file not found
#include "cairo.h"
         ^
1 error generated.
In file included from ../../../../../contrib/hbcairo/transfor.c:47:
../../../../../contrib/hbcairo/hbcairo.h:53:10: fatal error: 'cairo.h' file not found
#include "cairo.h"
         ^
```
Can you try adding a `depends_on "cairo"` to the formula and see if that works?

**Comment by endersonmaia** [comment]
I added `depends_on :cairo` and it compiled fine.

I'm in doubt if it should be :
* `depends_on :cairo => :optional`
* `depends_on :cairo if build.with? "x11"`
* `depends_on :cairo => :optional if build.with? "x11"`

/cc @vszakats

**Comment by vszakats** [comment]
X11 support doesn't require `cairo`, but one independent component (`hbcairo` contrib) does, and if detected it will build against it.

**Comment by endersonmaia** [comment]
@vszakats and `hbcairo` doesn't require X11, right ?

**Comment by vszakats** [comment]
@endersonmaia correct, `hbcairo` depends on `cairo` only.

**Comment by endersonmaia** [comment]
So, the question is, `depends_on :cairo => :optional` will allow homebrew's users to add `--with-cairo` when installing harbour.

But if cairo is already installed, the harbour build script will detect cairo and build the `hbcairo` contrib, even if it was not explicitly invoked `--with-cairo`.

Should this be addressed for all Harbour's contribs ?

**Comment by vszakats** [comment]
I'd think it should. If the goal is to tightly control Harbour's dependencies, maybe the best is to not let Harbour autodetect them, but pass location of headers via the `HB_WITH_<COMPONENT>` envvar, or the value `no` if we don't want it to find that specific component. (All this is only supposed to work with 3.4 HEAD, that includes the patch referenced in the linked 3.4 discussion)

Then cross fingers that everything pans out correctly.

**Comment by mikemcquaid** [comment]
> depends_on :cairo if build.with? "x11"

This seems like the easiest option.

> If the goal is to tightly control Harbour's dependencies, maybe the best is to not let Harbour autodetect them, but pass location of headers via the HB_WITH_<COMPONENT> envvars, or the value no if we don't want it to find that specific component.

This seems like the best option.

**Comment by endersonmaia** [comment]
@vszakats I could't find HB_WITH_CAIRO on Harbour's README.

And when compiling it with just with `HB_BUILD_CONTRIBS=cairo`, through homebrew, `libhbcairo.a` wasn't available.

My strategy was have all contribs as `:optional` and to feed a `contribs` array for each `--with-<contrib>` during install.

And we end up with `HB_BUILD_CONTRIBS=cairo [<other> ...].` before calling `make`.

**Comment by vszakats** [comment]
It's intentional, README doesn't cover anything `contrib` related. `contrib`s are meant to be self-contained and managed independently from Harbour core.

`HB_WITH_*` macros are listed in `.hbp` files in their `-depcontrol=` lines. You can list them using command:
```bash
contrib $ grep HB_WITH_ $(find . -name *.hbp)
```

Using `HB_BUILD_CONTRIBS=` will merely tell the build process which contribs to deal with. It won't affect how/where/if their dependencies are detected.

**Comment by endersonmaia** [comment]
Ok, I'll use that info and try to make a solution for the harbour formula when I get the time.

**Comment by MikeMcQuaid** [comment]
If this is still broken: we'll accept PRs for this but we're not actively working on it at this time.
